function pattern = survey_ConcurScatter_funcReconstructPattern(...
    excitationSymbols,pos,rem)
%survey_ConcurScatter_funcReconstructPattern Reconstruct a CS pattern.
%   Rows are received FFT bins and columns are OFDM symbols. This is the
%   same eight-term integer/fractional cyclic-shift approximation used by
%   the original ConcurScatter simulation scripts.

pattern = ...
    circshift(excitationSymbols,pos)*...
        sinc(-rem)*exp(-1i*pi*-rem)+...
    circshift(excitationSymbols,pos+1)*...
        sinc(1-rem)*exp(-1i*pi*(1-rem))+...
    circshift(excitationSymbols,pos+2)*...
        sinc(2-rem)*exp(-1i*pi*(2-rem))+...
    circshift(excitationSymbols,pos-1)*...
        sinc(-1-rem)*exp(-1i*pi*(-1-rem))+...
    circshift(excitationSymbols,pos+3)*...
        sinc(3-rem)*exp(-1i*pi*(3-rem))+...
    circshift(excitationSymbols,pos-2)*...
        sinc(-2-rem)*exp(-1i*pi*(-2-rem))+...
    circshift(excitationSymbols,pos+4)*...
        sinc(4-rem)*exp(-1i*pi*(4-rem))+...
    circshift(excitationSymbols,pos-3)*...
        sinc(-3-rem)*exp(-1i*pi*(-3-rem));
end
